from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path("menu/", views.menu, name = 'menu'),
    path("contact/", views.contact, name="contact"),
    path("register/", views.userregister, name = 'register'),
    path("login/", views.userlogin, name = 'login'),
    path("logout/", views.userlogout, name = 'logout'),
    path("profile/", views.profile, name="profile"),
    path("manager/", views.manager_dashboard, name = 'manager_dashboard'),
    path("manager/mark-payment-paid/<int:payment_id>/", views.manager_mark_payment_paid, name="manager_mark_payment_paid"),
    path("admin-dashboard/", views.admin_dashboard, name = 'admin_dashboard'),
    path("manager/confirm-order/<int:order_id>/", views.confirm_order, name = 'confirm_order'),
    path('checkout/', views.checkout, name = 'checkout'),
    path("book-table/", views.book_table, name = 'book_table'),
    path("reservation-confirmation/", views.reservation_confirmation, name = 'reservation_confirmation'),
    path("reservation-payment/", views.reservation_payment, name = 'reservation_payment'),
    path("manager/confirm-reservation/<int:reservation_id>/", views.confirm_reservation, name = 'confirm_reservation'),
    path("table-invoice/<int:reservation_id>/", views.table_invoice, name ='table_invoice'),
    path("my-reservation/", views.my_reservation, name = 'my_reservation'),
    path( "add-to-cart/<int:menu_item_id>/", views.add_to_cart, name='add_to_cart'),
    path("cart/", views.cart, name='cart'),
    path("cart/increase/<int:item_id>/", views.increase_quantity, name = 'increase_quantity'),
    path("cart/decrease/<int:item_id>/", views.decrease_quantity, name = 'decrease_quantity'),
    path("cart/remove/<int:item_id>/", views.remove_from_cart, name = 'remove_from_cart'),
    path("cart/clear/", views.clear_cart, name = "clear_cart"),
    path("my-orders/", views.my_orders, name = 'my_orders'),
    path("order-invoice/<int:order_id>/", views.order_invoice, name = 'order_invoice'),
    path("order-tracking/<int:order_id>/", views.order_tracking, name = 'order_tracking'),
    path("kitchen/", views.kitchen_orders, name = 'kitchen_orders'),
    path("kitchen/start-preparing/<int:order_id>/", views.start_preparing, name = 'start_preparing'),
    path("kitchen/mark-ready/<int:order_id>/", views.mark_ready, name = 'mark_ready'),
    path("kitchen/complete-order/<int:order_id>/", views.complete_order, name = 'complete_order'),
    path("inventory/", views.inventory, name = 'inventory'),
    path( "inventory/add-transaction/", views.add_stock_transaction, name = 'add_stock_transaction'),
    path("inventory/transactions/", views.stock_transactions, name = 'stock_transactions'),
    path("inventory/issue-to-kitchen/", views.issue_stock_to_kitchen, name = 'issue_stock_to_kitchen'),
    path("inventory/kitchen-stock/", views.kitchen_stock, name = 'kitchen_stock'),
    path( "payment/<int:order_id>/", views.payment, name = 'payment'),
    
]