# Generated by Django 6.1.1 on 2026-09-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenueItem',
            new_name='MenuItem',
        ),
    ]
