# Generated by Django 6.1.1 on 2026-09-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuitem',
            new_name='menu_item',
        ),
    ]
