# Generated by Django 6.1.1 on 2026-09-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.inventoryitem')),
            ],
        ),
    ]
