# Generated by Django 6.1.1 on 2026-09-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_kitchenstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('issue', 'Stock Issue'), ('consumption', 'Consumption'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
