# Generated by Django 6.1.1 on 2026-09-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_order_gst_amount_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
