# Generated by Django 6.1.1 on 2026-09-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_order_gst_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
            ],
        ),
    ]
