# Generated by Django 6.1.1 on 2026-09-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafesetting',
            name='about',
            field=models.TextField(default='Local:Byte Cafe'),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='address',
            field=models.CharField(default='Hazaribagh, Jharkhand', max_length=200),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='cafe_name',
            field=models.CharField(default='Local:Byte', max_length=100),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='closing_time',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='opening_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='tagline',
            field=models.CharField(default='Sip. Script. Savor.', max_length=200),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
