# Generated by Django 6.1.1 on 2026-09-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_cafesetting_about_cafesetting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafesetting',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafesetting',
            name='special_offer_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
